<?php

// config for Rahat1994/SparkcommerceMultivendor
return [
    'table_prefix' => 'sc_mv_',
    'admin_role' => 'scmv_admin',
    'vendor_owner_role' => 'scmv_vendor_owner',
    'customer_role' => 'scmv_customer',
    'default_role' => 'scmv_customer',
    'vendor_manager_role' => 'scmv_vendor_manager',
    'admin_permissions' => [
        'view_vendor_profile' => 'View Vendor Profile',
        'create_vendor' => 'Create Vendor',
        'edit_vendor' => 'Edit Vendor',
        'delete_vendor' => 'Delete Vendor',
        'view_vendor_request' => 'View Vendor Request',
        'create_vendor_request' => 'Create Vendor Request',
        'edit_vendor_request' => 'Edit Vendor Request',
        'delete_vendor_request' => 'Delete Vendor Request',
        'view_vendor_manager' => 'View Vendor Manager',
        'create_vendor_manager' => 'Create Vendor Manager',
        'edit_vendor_manager' => 'Edit Vendor Manager',
        'delete_vendor_manager' => 'Delete Vendor Manager',
        'view_vendor_owner' => 'View Vendor Owner',
        'create_vendor_owner' => 'Create Vendor Owner',
        'edit_vendor_owner' => 'Edit Vendor Owner',
        'delete_vendor_owner' => 'Delete Vendor Owner',
        'view_vendor_product' => 'View Vendor Product',
        'create_vendor_product' => 'Create Vendor Product',
        'edit_vendor_product' => 'Edit Vendor Product',
        'delete_vendor_product' => 'Delete Vendor Product',
        'view_vendor_order' => 'View Vendor Order',
        'create_vendor_order' => 'Create Vendor Order',
        'edit_vendor_order' => 'Edit Vendor Order',
        'delete_vendor_order' => 'Delete Vendor Order',
        'view_vendor_order_item' => 'View Vendor Order Item',
        'create_vendor_order_item' => 'Create Vendor Order Item',
        'edit_vendor_order_item' => 'Edit Vendor Order Item',
        'delete_vendor_order_item' => 'Delete Vendor Order Item',
        'view_vendor_order_status' => 'View Vendor Order Status',
        'create_vendor_order_status' => 'Create Vendor Order Status',
        'edit_vendor_order_status' => 'Edit Vendor Order Status',
        'delete_vendor_order_status' => 'Delete Vendor Order Status',
        'view_vendor_order_payment' => 'View Vendor Order Payment',
        'create_vendor_order_payment' => 'Create Vendor Order Payment',
        'edit_vendor_order_payment' => 'Edit Vendor Order Payment',
        'delete_vendor_order_payment' => 'Delete Vendor Order Payment',
        'view_vendor_order_shipping' => 'View Vendor Order Shipping',
        'create_vendor_order_shipping' => 'Create Vendor Order Shipping',
        'edit_vendor_order_shipping' => 'Edit Vendor Order Shipping',
        'delete_vendor_order_shipping' => 'Delete Vendor Order Shipping',
    ],
    'vendor_owner_permissions' => [
        'view_own_vendor_profile' => 'View own vendor profile',
        'edit_own_vendor_profile' => 'Edit own vendor profile',
        'view_own_vendor_product' => 'View Own Vendor Product',
        'create_own_vendor_product' => 'Create Own Vendor Product',
        'edit_own_vendor_product' => 'Edit Own Vendor Product',
        'delete_own_vendor_product' => 'Delete Own Vendor Product',
        'view_own_vendor_order' => 'View Own Vendor Order',
        'create_own_vendor_order' => 'Create Own Vendor Order',
        'edit_own_vendor_order' => 'Edit Own Vendor Order',
        'delete_own_vendor_order' => 'Delete Own Vendor Order',
        'view_own_vendor_order_item' => 'View Own Vendor Order Item',
        'create_own_vendor_order_item' => 'Create Own Vendor Order Item',
        'edit_own_vendor_order_item' => 'Edit Own Vendor Order Item',
        'delete_own_vendor_order_item' => 'Delete Own Vendor Order Item',
        'view_own_vendor_order_status' => 'View Own Vendor Order Status',
        'create_own_vendor_order_status' => 'Create Own Vendor Order Status',
        'edit_own_vendor_order_status' => 'Edit Own Vendor Order Status',
        'delete_own_vendor_order_status' => 'Delete Own Vendor Order Status',
        'view_own_vendor_order_payment' => 'View Own Vendor Order Payment',
        'create_own_vendor_order_payment' => 'Create Own Vendor Order Payment',
        'edit_own_vendor_order_payment' => 'Edit Own Vendor Order Payment',
        'delete_own_vendor_order_payment' => 'Delete Own Vendor Order Payment',
        'view_own_vendor_order_shipping' => 'View Own Vendor Order Shipping',
        'create_own_vendor_order_shipping' => 'Create Own Vendor Order Shipping',
        'edit_own_vendor_order_shipping' => 'Edit Own Vendor Order Shipping',
        'delete_own_vendor_order_shipping' => 'Delete Own Vendor Order Shipping',
    ],

];
